import type { Metadata } from "next";
import { Geist_Mono } from "next/font/google";
import { Grain } from "@/components/ui/grain";
import { Vignette } from "@/components/ui/vignette";
import { Providers } from "@/app/providers";
import Footer from "@/components/footer";
import "./globals.css";

const geistMono = Geist_Mono({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistMono.variable} antialiased font-mono min-h-screen`}
      >
        <Grain />
        <Vignette />
        <Providers>{children}</Providers>
        <Footer />
      </body>
    </html>
  );
}
